### ISSUE TITLE
AngularJS1.5.7 の導入

### ISSUE THREAD

**Issue by fwuprj** [fwuprj/fwu#16]
AngularJS1.5.7 の導入を行う。

**Comment by fwuprj** [comment]
以下を参考にする。

* https://medium.com/@ranostaj/cakephp-3-login-with-angularjs-7f89bab4c20#.7xuma69yg

**Comment by fwuprj** [comment]
index と view を API の振る舞いに変更する。

**Comment by fwuprj** [comment]
API については以下を参照。
http://qiita.com/ukisoft/items/a3362cea47e937b57070

**Comment by fwuprj** [comment]
サーバー/クライアント間の JSON  の交換については以下を参照。
http://qiita.com/laco0416/items/edfa917583af4593ad6c

**Comment by fwuprj** [comment]
もう ES6 の時代が近づいてきてるのか

**Comment by fwuprj** [comment]
$routeParams が取れんな。仕事してないかわいがミスったか。

**Comment by fwuprj** [comment]
調査は明日以降に行う。

**Comment by fwuprj** [comment]
http://www.w3schools.com/angular/tryit.asp?filename=try_ng_routing
を見ると AngularJS の route の概念の捉え方を間違ってる可能性あり。

**Comment by fwuprj** [comment]
ああ、間違ってるわ。SPAってそういうことか。

**Comment by fwuprj** [comment]
目的の解らしきものを見つける。
http://stackoverflow.com/questions/11063673/whats-the-most-concise-way-to-read-query-parameters-in-angularjs

**Comment by fwuprj** [comment]
\(´・ω・｀)/

**Comment by fwuprj** [comment]
これはパラメーター取得の場合なんね(´・ω・｀)ﾍｰ

**Comment by fwuprj** [comment]
強引にURLからidを取得。

**Comment by fwuprj** [comment]
<a> が機能しないので以下を参照。

http://stackoverflow.com/questions/19773682/angularjs-a-tag-links-not-working

**Comment by fwuprj** [comment]
これディレクトリ構造どうしたらええんやろ

**Comment by fwuprj** [comment]
factoryパターンが推奨されている？
http://stackoverflow.com/questions/21919962/share-data-between-angularjs-controllers

**Comment by fwuprj** [comment]
以下を参考にディレクトリ構造を変更する。
http://qiita.com/suetake/items/f61b4413eefeb60ef7fb

**Comment by fwuprj** [comment]
休むのん(´・ω・｀)

**Comment by kouMatsumoto** [comment]
その記事はたぶん少し古くて、Angular1.5から導入されたcomponent機能で大きく変わっていると思います。

とりあえずおすすめの構成としては
https://scotch.io/tutorials/angularjs-best-practices-directory-structure
に倣って、

app/
----- components/
---------- foo.component.js
---------- foo-kebab.component.js
----- services/
---------- bar.service.js
---------- bar-kebab.service.js
----- js/
---------- bootstrap.js
---------- jquery.js
----- app.js

みたいな感じです。
ファイルの名前はkebab-case.component.js、クラスの名前はCamelCaseComponentとしているのは、Angular2公式を参考にした命名規則です。
https://angular.io/docs/ts/latest/quickstart.html

**Comment by fwuprj** [comment]
おお、ありがとう
その構成と命名規則で構築してみる

**Comment by fwuprj** [comment]
再開するのん(｀・ω・´)

**Comment by fwuprj** [comment]
CakePHP3 のディレクトリ構造と共存させるならこっちのほうがいいかな
bootstrap とかは CakePHP3 単体でも使うと思うんだよね
lib/ というかフレームワークだけど

```
webroot/js/
---- lib/
-------- angular/
------------ angular.min.js
-------- bootstrap/
------------ bootstrap.min.js
---- app/
-------- components/
------------ foo.component.js
------------ foo-kebab.component.js
-------- services/
------------ bar.service.js
------------ bar-kebab.service.js
-------- app.js
```

**Comment by kouMatsumoto** [comment]
とりあえずはそれでいいと思う
本格的なSPAになる場合はまた再構成すれば良いと思うので、現状はあまりこだわらずに開発進めた方がいいと思う

**Comment by fwuprj** [comment]
おｋ
進めるお

**Comment by fwuprj** [comment]
とりあえず完了とする。
